import '../models/country.dart';

final List<Country> dummyCountries = [
  Country(country: 'Afghanistan', capital: 'Kabul', flagUrl: 'https://flagcdn.com/w640/af.png'),
  Country(country: 'Albania', capital: 'Tirana', flagUrl: 'https://flagcdn.com/w640/al.png'),
  Country(country: 'Algeria', capital: 'Algiers', flagUrl: 'https://flagcdn.com/w640/dz.png'),
  Country(country: 'Andorra', capital: 'Andorra la Vella', flagUrl: 'https://flagcdn.com/w640/ad.png'),
  Country(country: 'Angola', capital: 'Luanda', flagUrl: 'https://flagcdn.com/w640/ao.png'),
  Country(country: 'Antigua and Barbuda', capital: 'Saint John\'s', flagUrl: 'https://flagcdn.com/w640/ag.png'),
  Country(country: 'Argentina', capital: 'Buenos Aires', flagUrl: 'https://flagcdn.com/w640/ar.png'),
  Country(country: 'Armenia', capital: 'Yerevan', flagUrl: 'https://flagcdn.com/w640/am.png'),
  Country(country: 'Australia', capital: 'Canberra', flagUrl: 'https://flagcdn.com/w640/au.png'),
  Country(country: 'Austria', capital: 'Vienna', flagUrl: 'https://flagcdn.com/w640/at.png'),
  Country(country: 'Azerbaijan', capital: 'Baku', flagUrl: 'https://flagcdn.com/w640/az.png'),
  Country(country: 'Bahamas', capital: 'Nassau', flagUrl: 'https://flagcdn.com/w640/bs.png'),
  Country(country: 'Bahrain', capital: 'Manama', flagUrl: 'https://flagcdn.com/w640/bh.png'),
  Country(country: 'Bangladesh', capital: 'Dhaka', flagUrl: 'https://flagcdn.com/w640/bd.png'),
  Country(country: 'Barbados', capital: 'Bridgetown', flagUrl: 'https://flagcdn.com/w640/bb.png'),
  Country(country: 'Belarus', capital: 'Minsk', flagUrl: 'https://flagcdn.com/w640/by.png'),
  Country(country: 'Belgium', capital: 'Brussels', flagUrl: 'https://flagcdn.com/w640/be.png'),
  Country(country: 'Belize', capital: 'Belmopan', flagUrl: 'https://flagcdn.com/w640/bz.png'),
  Country(country: 'Benin', capital: 'Porto-Novo', flagUrl: 'https://flagcdn.com/w640/bj.png'),
  Country(country: 'Bhutan', capital: 'Thimphu', flagUrl: 'https://flagcdn.com/w640/bt.png'),
  Country(country: 'Bolivia', capital: 'La Paz (administrative)', flagUrl: 'https://flagcdn.com/w640/bo.png'),
  Country(country: 'Bosnia and Herzegovina', capital: 'Sarajevo', flagUrl: 'https://flagcdn.com/w640/ba.png'),
  Country(country: 'Botswana', capital: 'Gaborone', flagUrl: 'https://flagcdn.com/w640/bw.png'),
  Country(country: 'Brazil', capital: 'Brasília', flagUrl: 'https://flagcdn.com/w640/br.png'),
  Country(country: 'Brunei', capital: 'Bandar Seri Begawan', flagUrl: 'https://flagcdn.com/w640/bn.png'),
  Country(country: 'Bulgaria', capital: 'Sofia', flagUrl: 'https://flagcdn.com/w640/bg.png'),
  Country(country: 'Burkina Faso', capital: 'Ouagadougou', flagUrl: 'https://flagcdn.com/w640/bf.png'),
  Country(country: 'Burundi', capital: 'Gitega', flagUrl: 'https://flagcdn.com/w640/bi.png'),
  Country(country: 'Cambodia', capital: 'Phnom Penh', flagUrl: 'https://flagcdn.com/w640/kh.png'),
  Country(country: 'Cameroon', capital: 'Yaoundé', flagUrl: 'https://flagcdn.com/w640/cm.png'),
  Country(country: 'Canada', capital: 'Ottawa', flagUrl: 'https://flagcdn.com/w640/ca.png'),
  Country(country: 'Cape Verde', capital: 'Praia', flagUrl: 'https://flagcdn.com/w640/cv.png'),
  Country(country: 'Central African Republic', capital: 'Bangui', flagUrl: 'https://flagcdn.com/w640/cf.png'),
  Country(country: 'Chad', capital: 'N\'Djamena', flagUrl: 'https://flagcdn.com/w640/td.png'),
  Country(country: 'Chile', capital: 'Santiago', flagUrl: 'https://flagcdn.com/w640/cl.png'),
  Country(country: 'China', capital: 'Pekin', flagUrl: 'https://flagcdn.com/w640/cn.png'),
  Country(country: 'Colombia', capital: 'Bogotá', flagUrl: 'https://flagcdn.com/w640/co.png'),
  Country(country: 'Comoros', capital: 'Moroni', flagUrl: 'https://flagcdn.com/w640/km.png'),
  Country(country: 'Democratic Republic of the Congo,', capital: 'Kinshasa', flagUrl: 'https://flagcdn.com/w640/cd.png'),
  Country(country: 'Republic of the Congo,', capital: 'Brazzaville', flagUrl: 'https://flagcdn.com/w640/cg.png'),
  Country(country: 'Costa Rica', capital: 'San José', flagUrl: 'https://flagcdn.com/w640/cr.png'),
  Country(country: 'Côte d\'Ivoire', capital: 'Yamoussoukro', flagUrl: 'https://flagcdn.com/w640/ci.png'),
  Country(country: 'Croatia', capital: 'Zagreb', flagUrl: 'https://flagcdn.com/w640/hr.png'),
  Country(country: 'Cuba', capital: 'Havana', flagUrl: 'https://flagcdn.com/w640/cu.png'),
  Country(country: 'Cyprus', capital: 'Nicosia', flagUrl: 'https://flagcdn.com/w640/cy.png'),
  Country(country: 'Czech Republic', capital: 'Prague', flagUrl: 'https://flagcdn.com/w640/cz.png'),
  Country(country: 'Denmark', capital: 'Copenhagen', flagUrl: 'https://flagcdn.com/w640/dk.png'),
  Country(country: 'Djibouti', capital: 'Djibouti', flagUrl: 'https://flagcdn.com/w640/dj.png'),
  Country(country: 'Dominica', capital: 'Roseau', flagUrl: 'https://flagcdn.com/w640/dm.png'),
  Country(country: 'Dominican Republic', capital: 'Santo Domingo', flagUrl: 'https://flagcdn.com/w640/do.png'),
  Country(country: 'East Timor', capital: 'Dili', flagUrl: 'https://flagcdn.com/w640/tl.png'),
  Country(country: 'Ecuador', capital: 'Quito', flagUrl: 'https://flagcdn.com/w640/ec.png'),
  Country(country: 'Egypt', capital: 'Cairo', flagUrl: 'https://flagcdn.com/w640/eg.png'),
  Country(country: 'El Salvador', capital: 'San Salvador', flagUrl: 'https://flagcdn.com/w640/sv.png'),
  Country(country: 'Equatorial Guinea', capital: 'Malabo', flagUrl: 'https://flagcdn.com/w640/gq.png'),
  Country(country: 'Eritrea', capital: 'Asmara', flagUrl: 'https://flagcdn.com/w640/er.png'),
  Country(country: 'Estonia', capital: 'Tallinn', flagUrl: 'https://flagcdn.com/w640/ee.png'),
  Country(country: 'Eswatini', capital: 'Mbabane', flagUrl: 'https://flagcdn.com/w640/sz.png'),
  Country(country: 'Ethiopia', capital: 'Addis Ababa', flagUrl: 'https://flagcdn.com/w640/et.png'),
  Country(country: 'Fiji', capital: 'Suva', flagUrl: 'https://flagcdn.com/w640/fj.png'),
  Country(country: 'Finland', capital: 'Helsinki', flagUrl: 'https://flagcdn.com/w640/fi.png'),
  Country(country: 'France', capital: 'Paris', flagUrl: 'https://flagcdn.com/w640/fr.png'),
  Country(country: 'Gabon', capital: 'Libreville', flagUrl: 'https://flagcdn.com/w640/ga.png'),
  Country(country: 'Gambia', capital: 'Banjul', flagUrl: 'https://flagcdn.com/w640/gm.png'),
  Country(country: 'Georgia', capital: 'Tbilisi', flagUrl: 'https://flagcdn.com/w640/ge.png'),
  Country(country: 'Germany', capital: 'Berlin', flagUrl: 'https://flagcdn.com/w640/de.png'),
  Country(country: 'Ghana', capital: 'Accra', flagUrl: 'https://flagcdn.com/w640/gh.png'),
  Country(country: 'Greece', capital: 'Athens', flagUrl: 'https://flagcdn.com/w640/gr.png'),
  Country(country: 'Grenada', capital: 'St. George\'s', flagUrl: 'https://flagcdn.com/w640/gd.png'),
  Country(country: 'Guatemala', capital: 'Guatemala City', flagUrl: 'https://flagcdn.com/w640/gt.png'),
  Country(country: 'Guinea', capital: 'Conakry', flagUrl: 'https://flagcdn.com/w640/gn.png'),
  Country(country: 'Guinea-Bissau', capital: 'Bissau', flagUrl: 'https://flagcdn.com/w640/gw.png'),
    Country(country: 'Guyana', capital: 'Georgetown', flagUrl: 'https://flagcdn.com/w640/gy.png'),
  Country(country: 'Haiti', capital: 'Port-au-Prince', flagUrl: 'https://flagcdn.com/w640/ht.png'),
  Country(country: 'Honduras', capital: 'Tegucigalpa', flagUrl: 'https://flagcdn.com/w640/hn.png'),
  Country(country: 'Hungary', capital: 'Budapest', flagUrl: 'https://flagcdn.com/w640/hu.png'),
  Country(country: 'Iceland', capital: 'Reykjavik', flagUrl: 'https://flagcdn.com/w640/is.png'),
  Country(country: 'India', capital: 'New Delhi', flagUrl: 'https://flagcdn.com/w640/in.png'),
  Country(country: 'Indonesia', capital: 'Jakarta', flagUrl: 'https://flagcdn.com/w640/id.png'),
  Country(country: 'Iran', capital: 'Tehran', flagUrl: 'https://flagcdn.com/w640/ir.png'),
  Country(country: 'Iraq', capital: 'Baghdad', flagUrl: 'https://flagcdn.com/w640/iq.png'),
  Country(country: 'Ireland', capital: 'Dublin', flagUrl: 'https://flagcdn.com/w640/ie.png'),
  Country(country: 'Israel', capital: 'Jerusalem', flagUrl: 'https://flagcdn.com/w640/il.png'),
  Country(country: 'Italy', capital: 'Rome', flagUrl: 'https://flagcdn.com/w640/it.png'),
  Country(country: 'Jamaica', capital: 'Kingston', flagUrl: 'https://flagcdn.com/w640/jm.png'),
  Country(country: 'Japan', capital: 'Tokyo', flagUrl: 'https://flagcdn.com/w640/jp.png'),
  Country(country: 'Jordan', capital: 'Amman', flagUrl: 'https://flagcdn.com/w640/jo.png'),
  Country(country: 'Kazakhstan', capital: 'Nur-Sultan', flagUrl: 'https://flagcdn.com/w640/kz.png'),
  Country(country: 'Kenya', capital: 'Nairobi', flagUrl: 'https://flagcdn.com/w640/ke.png'),
  Country(country: 'Kiribati', capital: 'South Tarawa', flagUrl: 'https://flagcdn.com/w640/ki.png'),
  Country(country: 'Kosovo', capital: 'Pristina', flagUrl: 'https://flagcdn.com/w640/xk.png'),
  Country(country: 'Kuwait', capital: 'Kuwait City', flagUrl: 'https://flagcdn.com/w640/kw.png'),
  Country(country: 'Kyrgyzstan', capital: 'Bishkek', flagUrl: 'https://flagcdn.com/w640/kg.png'),
  Country(country: 'Laos', capital: 'Vientiane', flagUrl: 'https://flagcdn.com/w640/la.png'),
  Country(country: 'Latvia', capital: 'Riga', flagUrl: 'https://flagcdn.com/w640/lv.png'),
  Country(country: 'Lebanon', capital: 'Beirut', flagUrl: 'https://flagcdn.com/w640/lb.png'),
  Country(country: 'Lesotho', capital: 'Maseru', flagUrl: 'https://flagcdn.com/w640/ls.png'),
   Country(country: 'Liberia', capital: 'Monrovia', flagUrl: 'https://flagcdn.com/w640/lr.png'),
  Country(country: 'Libya', capital: 'Tripoli', flagUrl: 'https://flagcdn.com/w640/ly.png'),
  Country(country: 'Liechtenstein', capital: 'Vaduz', flagUrl: 'https://flagcdn.com/w640/li.png'),
  Country(country: 'Lithuania', capital: 'Vilnius', flagUrl: 'https://flagcdn.com/w640/lt.png'),
  Country(country: 'Luxembourg', capital: 'Luxembourg City', flagUrl: 'https://flagcdn.com/w640/lu.png'),
  Country(country: 'Madagascar', capital: 'Antananarivo', flagUrl: 'https://flagcdn.com/w640/mg.png'),
  Country(country: 'Malawi', capital: 'Lilongwe', flagUrl: 'https://flagcdn.com/w640/mw.png'),
  Country(country: 'Malaysia', capital: 'Kuala Lumpur', flagUrl: 'https://flagcdn.com/w640/my.png'),
  Country(country: 'Maldives', capital: 'Male', flagUrl: 'https://flagcdn.com/w640/mv.png'),
  Country(country: 'Mali', capital: 'Bamako', flagUrl: 'https://flagcdn.com/w640/ml.png'),
  Country(country: 'Malta', capital: 'Valletta', flagUrl: 'https://flagcdn.com/w640/mt.png'),
  Country(country: 'Marshall Islands', capital: 'Majuro', flagUrl: 'https://flagcdn.com/w640/mh.png'),
  Country(country: 'Mauritania', capital: 'Nouakchott', flagUrl: 'https://flagcdn.com/w640/mr.png'),
  Country(country: 'Mauritius', capital: 'Port Louis', flagUrl: 'https://flagcdn.com/w640/mu.png'),
  Country(country: 'Mexico', capital: 'Mexico City', flagUrl: 'https://flagcdn.com/w640/mx.png'),
  Country(country: 'Micronesia', capital: 'Palikir', flagUrl: 'https://flagcdn.com/w640/fm.png'),
  Country(country: 'Moldova', capital: 'Chisinau', flagUrl: 'https://flagcdn.com/w640/md.png'),
  Country(country: 'Monaco', capital: 'Monaco', flagUrl: 'https://flagcdn.com/w640/mc.png'),
  Country(country: 'Mongolia', capital: 'Ulaanbaatar', flagUrl: 'https://flagcdn.com/w640/mn.png'),
  Country(country: 'Montenegro', capital: 'Podgorica', flagUrl: 'https://flagcdn.com/w640/me.png'),
  Country(country: 'Morocco', capital: 'Rabat', flagUrl: 'https://flagcdn.com/w640/ma.png'),
  Country(country: 'Mozambique', capital: 'Maputo', flagUrl: 'https://flagcdn.com/w640/mz.png'),
  Country(country: 'Myanmar', capital: 'Naypyidaw', flagUrl: 'https://flagcdn.com/w640/mm.png'),
  Country(country: 'Namibia', capital: 'Windhoek', flagUrl: 'https://flagcdn.com/w640/na.png'),
    Country(country: 'Nauru', capital: 'Yaren District', flagUrl: 'https://flagcdn.com/w640/nr.png'),
  Country(country: 'Nepal', capital: 'Kathmandu', flagUrl: 'https://flagcdn.com/w640/np.png'),
  Country(country: 'Netherlands', capital: 'Amsterdam', flagUrl: 'https://flagcdn.com/w640/nl.png'),
  Country(country: 'New Zealand', capital: 'Wellington', flagUrl: 'https://flagcdn.com/w640/nz.png'),
  Country(country: 'Nicaragua', capital: 'Managua', flagUrl: 'https://flagcdn.com/w640/ni.png'),
  Country(country: 'Niger', capital: 'Niamey', flagUrl: 'https://flagcdn.com/w640/ne.png'),
  Country(country: 'Nigeria', capital: 'Abuja', flagUrl: 'https://flagcdn.com/w640/ng.png'),
  Country(country: 'North Korea', capital: 'Pyongyang', flagUrl: 'https://flagcdn.com/w640/kp.png'),
  Country(country: 'North Macedonia', capital: 'Skopje', flagUrl: 'https://flagcdn.com/w640/mk.png'),
  Country(country: 'Norway', capital: 'Oslo', flagUrl: 'https://flagcdn.com/w640/no.png'),
  Country(country: 'Oman', capital: 'Muscat', flagUrl: 'https://flagcdn.com/w640/om.png'),
  Country(country: 'Pakistan', capital: 'Islamabad', flagUrl: 'https://flagcdn.com/w640/pk.png'),
  Country(country: 'Palau', capital: 'Ngerulmud', flagUrl: 'https://flagcdn.com/w640/pw.png'),
  Country(country: 'Panama', capital: 'Panama City', flagUrl: 'https://flagcdn.com/w640/pa.png'),
  Country(country: 'Papua New Guinea', capital: 'Port Moresby', flagUrl: 'https://flagcdn.com/w640/pg.png'),
  Country(country: 'Paraguay', capital: 'Asuncion', flagUrl: 'https://flagcdn.com/w640/py.png'),
  Country(country: 'Peru', capital: 'Lima', flagUrl: 'https://flagcdn.com/w640/pe.png'),
  Country(country: 'Philippines', capital: 'Manila', flagUrl: 'https://flagcdn.com/w640/ph.png'),
  Country(country: 'Poland', capital: 'Warsaw', flagUrl: 'https://flagcdn.com/w640/pl.png'),
  Country(country: 'Portugal', capital: 'Lisbon', flagUrl: 'https://flagcdn.com/w640/pt.png'),
  Country(country: 'Qatar', capital: 'Doha', flagUrl: 'https://flagcdn.com/w640/qa.png'),
  Country(country: 'Romania', capital: 'Bucharest', flagUrl: 'https://flagcdn.com/w640/ro.png'),
  Country(country: 'Russia', capital: 'Moscow', flagUrl: 'https://flagcdn.com/w640/ru.png'),
  Country(country: 'Rwanda', capital: 'Kigali', flagUrl: 'https://flagcdn.com/w640/rw.png'),
  Country(country: 'Saint Kitts and Nevis', capital: 'Basseterre', flagUrl: 'https://flagcdn.com/w640/kn.png'),
  Country(country: 'Saint Kitts and Nevis', capital: 'Basseterre', flagUrl: 'https://flagcdn.com/w640/kn.png'),
  Country(country: 'Saint Lucia', capital: 'Castries', flagUrl: 'https://flagcdn.com/w640/lc.png'),
  Country(country: 'Saint Vincent and the Grenadines', capital: 'Kingstown', flagUrl: 'https://flagcdn.com/w640/vc.png'),
  Country(country: 'Samoa', capital: 'Apia', flagUrl: 'https://flagcdn.com/w640/ws.png'),
  Country(country: 'San Marino', capital: 'San Marino', flagUrl: 'https://flagcdn.com/w640/sm.png'),
  Country(country: 'Sao Tome and Principe', capital: 'Sao Tome', flagUrl: 'https://flagcdn.com/w640/st.png'),
  Country(country: 'Saudi Arabia', capital: 'Riyadh', flagUrl: 'https://flagcdn.com/w640/sa.png'),
  Country(country: 'Senegal', capital: 'Dakar', flagUrl: 'https://flagcdn.com/w640/sn.png'),
  Country(country: 'Serbia', capital: 'Belgrade', flagUrl: 'https://flagcdn.com/w640/rs.png'),
  Country(country: 'Seychelles', capital: 'Victoria', flagUrl: 'https://flagcdn.com/w640/sc.png'),
  Country(country: 'Sierra Leone', capital: 'Freetown', flagUrl: 'https://flagcdn.com/w640/sl.png'),
  Country(country: 'Singapore', capital: 'Singapore', flagUrl: 'https://flagcdn.com/w640/sg.png'),
  Country(country: 'Slovakia', capital: 'Bratislava', flagUrl: 'https://flagcdn.com/w640/sk.png'),
  Country(country: 'Slovenia', capital: 'Ljubljana', flagUrl: 'https://flagcdn.com/w640/si.png'),
  Country(country: 'Solomon Islands', capital: 'Honiara', flagUrl: 'https://flagcdn.com/w640/sb.png'),
  Country(country: 'Somalia', capital: 'Mogadishu', flagUrl: 'https://flagcdn.com/w640/so.png'),
  Country(country: 'South Africa', capital: 'Pretoria', flagUrl: 'https://flagcdn.com/w640/za.png'),
  Country(country: 'South Korea', capital: 'Seoul', flagUrl: 'https://flagcdn.com/w640/kr.png'),
  Country(country: 'South Sudan', capital: 'Juba', flagUrl: 'https://flagcdn.com/w640/ss.png'),
  Country(country: 'Spain', capital: 'Madrid', flagUrl: 'https://flagcdn.com/w640/es.png'),
  Country(country: 'Sri Lanka', capital: 'Sri Jayawardenepura Kotte', flagUrl: 'https://flagcdn.com/w640/lk.png'),
  Country(country: 'Sudan', capital: 'Khartoum', flagUrl: 'https://flagcdn.com/w640/sd.png'),
  Country(country: 'Suricountry', capital: 'Paramaribo', flagUrl: 'https://flagcdn.com/w640/sr.png'),
  Country(country: 'Sweden', capital: 'Stockholm', flagUrl: 'https://flagcdn.com/w640/se.png'),
  Country(country: 'Switzerland', capital: 'Bern', flagUrl: 'https://flagcdn.com/w640/ch.png'),
  Country(country: 'Syria', capital: 'Damascus', flagUrl: 'https://flagcdn.com/w640/sy.png'),
  Country(country: 'Taiwan', capital: 'Taipei', flagUrl: 'https://flagcdn.com/w640/tw.png'),
  Country(country: 'Tajikistan', capital: 'Dushanbe', flagUrl: 'https://flagcdn.com/w640/tj.png'),
  Country(country: 'Tanzania', capital: 'Dodoma', flagUrl: 'https://flagcdn.com/w640/tz.png'),
  Country(country: 'Thailand', capital: 'Bangkok', flagUrl: 'https://flagcdn.com/w640/th.png'),
  Country(country: 'Timor-Leste', capital: 'Dili', flagUrl: 'https://flagcdn.com/w640/tl.png'),
  Country(country: 'Togo', capital: 'Lome', flagUrl: 'https://flagcdn.com/w640/tg.png'),
  Country(country: 'Tonga', capital: "Nuku'alofa", flagUrl: 'https://flagcdn.com/w640/to.png'),
  Country(country: 'Trinidad and Tobago', capital: 'Port of Spain', flagUrl: 'https://flagcdn.com/w640/tt.png'),
  Country(country: 'Tunisia', capital: 'Tunis', flagUrl: 'https://flagcdn.com/w640/tn.png'),
  Country(country: 'Turkey', capital: 'Ankara', flagUrl: 'https://flagcdn.com/w640/tr.png'),
  Country(country: 'Turkmenistan', capital: 'Ashgabat', flagUrl: 'https://flagcdn.com/w640/tm.png'),
  Country(country: 'Tuvalu', capital: 'Funafuti', flagUrl: 'https://flagcdn.com/w640/tv.png'),
  Country(country: 'Uganda', capital: 'Kampala', flagUrl: 'https://flagcdn.com/w640/ug.png'),
  Country(country: 'Ukraine', capital: 'Kyiv', flagUrl: 'https://flagcdn.com/w640/ua.png'),
  Country(country: 'United Arab Emirates', capital: 'Abu Dhabi', flagUrl: 'https://flagcdn.com/w640/ae.png'),
  Country(country: 'United Kingdom', capital: 'London', flagUrl: 'https://flagcdn.com/w640/gb.png'),
  Country(country: 'United States of America', capital: 'Washington, D.C.', flagUrl: 'https://flagcdn.com/w640/us.png'),
  Country(country: 'Uruguay', capital: 'Montevideo', flagUrl: 'https://flagcdn.com/w640/uy.png'),
  Country(country: 'Uzbekistan', capital: 'Tashkent', flagUrl: 'https://flagcdn.com/w640/uz.png'),
  Country(country: 'Vanuatu', capital: 'Port Vila', flagUrl: 'https://flagcdn.com/w640/vu.png'),
  Country(country: 'Vatican City (Holy See)', capital: 'Vatican City', flagUrl: 'https://flagcdn.com/w640/va.png'),
  Country(country: 'Venezuela', capital: 'Caracas', flagUrl: 'https://flagcdn.com/w640/ve.png'),
  Country(country: 'Vietnam', capital: 'Hanoi', flagUrl: 'https://flagcdn.com/w640/vn.png'),
  Country(country: 'Yemen', capital: "Sana'a", flagUrl: 'https://flagcdn.com/w640/ye.png'),
  Country(country: 'Zambia', capital: 'Lusaka', flagUrl: 'https://flagcdn.com/w640/zm.png'),
  Country(country: 'Zimbabwe', capital: 'Harare', flagUrl: 'https://flagcdn.com/w640/zw.png')
];


